### ISSUE TITLE
Setting user properties

### ISSUE THREAD

**Issue by adlenafane** [kaesonho/react-i13n-ga#10]
Hi @kaesonho,
Would you be willing to integrate methods in this spirit -> https://github.com/adlenafane/react-i13n-mixpanel/pull/1/files

Or would you rather have the user update / re-instantiate the plugin

**Comment by adlenafane** [comment]
Opening the PR

**Comment by kaesonho** [comment]
thanks @adlenafane , the code looks good to me, however I'm thinking if users should access ga plugin instance directly and do whatever they need?

for example 

```js
var instance = ReactI13nGoogleAnalytics.getInstance();
instance.command( // do whatever they need
```
